### ISSUE TITLE
Aggregator not showing the main page when running in container

### ISSUE THREAD

**Issue by farrukharshad** [opendatakit/aggregate#107]
Greetings,

I am building a Docker container of the odkaggregator 1.4.15. The container starts fine but when I open the page just in the start it redirects to the main page, the main page keep on refreshing with following server exception in the logs. The same war file runs fine on my host machine. I believe the issue has to do something with the host-container port-forwarding. 

ODK Aggregator 1.4.15
JRE 8
Tomcat 8
useSSL = false

My container IP Address (odkaggregator host) = 172.18.0.3:8080
My host IP Address = 192.168.100.4:8080
Host to container port forwarded for 8080 to 8080

I am accessing the odkaggregator via 192.168.100.4:8080

Thanks

`
Sep 19, 2017 2:51:29 PM org.apache.catalina.core.ApplicationContext log
INFO: securityServiceImpl: ERROR: The serialization policy file '/aggregateui/C55E8F5A4E0A843C71E82F948E8CE147.gwt.rpc' was not found; did you forget to include it in this deployment?
Sep 19, 2017 2:51:29 PM org.apache.catalina.core.ApplicationContext log
INFO: securityServiceImpl: WARNING: Failed to get the SerializationPolicy 'C55E8F5A4E0A843C71E82F948E8CE147' for module 'http://192.168.100.4:8080/aggregateui/'; a legacy, 1.3.3 compatible, serialization policy will be used.  You may experience SerializationExceptions as a result.
Sep 19, 2017 2:51:29 PM org.apache.catalina.core.ApplicationContext log
SEVERE: Exception while dispatching incoming RPC call
com.google.gwt.user.client.rpc.SerializationException: Type 'org.opendatakit.common.security.client.exception.AccessDeniedException' was not assignable to 'com.google.gwt.user.client.rpc.IsSerializable' and did not have a custom field serializer.For security purposes, this type will not be serialized.: instance = org.opendatakit.common.security.client.exception.AccessDeniedException: Invalid request
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serialize(ServerSerializationStreamWriter.java:667)
	at com.google.gwt.user.client.rpc.impl.AbstractSerializationStreamWriter.writeObject(AbstractSerializationStreamWriter.java:130)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter$ValueWriter$8.write(ServerSerializationStreamWriter.java:153)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serializeValue(ServerSerializationStreamWriter.java:587)
	at com.google.gwt.user.server.rpc.RPC.encodeResponse(RPC.java:631)
	at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:419)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.opendatakit.common.security.spring.SecurityContextHolderAwareAuthPreservingRequestFilter.doFilter(SecurityContextHolderAwareAuthPreservingRequestFilter.java:66)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.www.DigestAuthenticationFilter.doFilter(DigestAuthenticationFilter.java:126)
	at org.opendatakit.common.security.spring.DigestAuthenticationFilter.doFilter(DigestAuthenticationFilter.java:40)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.opendatakit.common.security.spring.OutOfBandUserFilter.doFilter(OutOfBandUserFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.opendatakit.common.security.spring.Oauth2ResourceFilter.doFilter(Oauth2ResourceFilter.java:352)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.channel.ChannelProcessingFilter.doFilter(ChannelProcessingFilter.java:157)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2521)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2510)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by linl33** [comment]
Are you building your own Docker image or using [sync-endpoint-containers](https://github.com/opendatakit/sync-endpoint-containers)?

**Comment by farrukharshad** [comment]
Building my own docker image. Given below is my Dockerfile (which I have copied from another [Dockerfile](https://github.com/Kharatsa/odkaggregate) of odkaggregate of older version)


`FROM tomcat:8.0-jre8

ENV BUILD_DEPS='curl' \
    CONNECTORJ_MAJOR_VERSION='5' \
    CONNECTORJ_VERSION='5.1.38' \
    MYSQL_HOSTNAME='localhost' \
    MYSQL_PORT='3306' \
    ODK_PORT='8080' \
    ODK_PORT_SECURE='8443' \
    ODK_ADMIN_USER_EMAIL='mailto:admin@localhost' \
    ODK_USERNAME='admin' \
    ODK_INST_NAME='odkaggregate'

RUN apt-get update \
    && apt-get install -y ${BUILD_DEPS} --no-install-recommends \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*; exit 0

RUN curl -OL https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-${CONNECTORJ_VERSION}.tar.gz \
    && tar -xzf mysql-connector-java-${CONNECTORJ_VERSION}.tar.gz \
    && cp mysql-connector-java-$CONNECTORJ_VERSION/mysql-connector-java-${CONNECTORJ_VERSION}-bin.jar ${CATALINA_HOME}/lib/ \
    && rm -rf  mysql-connector-java-${CONNECTORJ_VERSION}/ mysql-connector-java-${CONNECTORJ_VERSION}.tar.gz

COPY run.sh /run.sh
COPY ODKAggregate.war /ODKAggregate.war
RUN chmod +x /run.sh

EXPOSE ${ODK_PORT}
ENTRYPOINT ["/run.sh"]`

Given below is my launch script

`
docker run --name=$AGGREGATE_CONTAINER_NAME \
  --link $MYSQL_HOSTNAME \
  --restart on-failure:10 \
  --network $PCLOUD_NETWORK \
  -p 8080:8080 \
  -e MYSQL_HOSTNAME=$MYSQL_HOSTNAME \
  -e MYSQL_DATABASE=$MYSQL_DATABASE \
  -e MYSQL_USER=$MYSQL_USER \
  -e MYSQL_PASS=$MYSQL_PASS \
  -e MYSQL_PORT=$MYSQL_PORT \
  -e ODK_PORT=$ODK_PORT \
  -e ODK_PORT_SECURE=$ODK_PORT_SECURE \
  -e ODK_HOSTNAME=$ODK_HOSTNAME \
  -e ODK_INST_NAME=$ODK_INST_NAME \
  odkaggregate:1.4.15.c
`

**Comment by linl33** [comment]
I see that you switched to [sync-endpoint-containers](https://github.com/opendatakit/sync-endpoint-containers) on #108 can we closed this issue?

**Comment by jbeorse** [comment]
To be clear, the [sync-endpoint-containers](https://github.com/opendatakit/sync-endpoint-containers) are suitable for use with the 2.0 mobile tools only. If you want support for [Collect](https://github.com/opendatakit/collect) you will need to use Aggregate.

**Comment by farrukharshad** [comment]
@jbeorse thanks for the clarification. 

Actually I want to use [ODK Aggregate](https://opendatakit.org/downloads/download-info/odk-aggregate-linux-x64-installer-run/). If [sync-endpoint-containers](https://github.com/opendatakit/sync-endpoint-containers) is not ODK Aggregate, then this issue is still valid and I will go with above approach.

**Comment by farrukharshad** [comment]
Can you please confirm odk-aggregate and sync-endpoint-containers are both different ?

**Comment by jbeorse** [comment]
Sorry, for the delay. I can confirm that sync-endpoint-containers are not ODK Aggregate. They are also not compatible with ODK Collect. 

sync-endpoint-containers do contain code that started in ODK Aggregate, but they have diverged and only support the ODK 2.0 tools. The 2.0 tools are still in pre-release, but will be released at the end of this month. You can see our latest release candidate here: https://forum.opendatakit.org/t/odk-2-0-tool-suite-rev-212-release-candidates-now-available/9931

And, just to clarify, the 2.0 tools will NOT be replacing the 1.x tools. They service different purposes and we are working on renaming the 2.0 tools to something else to make this clearer.

**Comment by jbeorse** [comment]
You might be able to reuse some of the configuration from the sync-endpoint-containers. Their setup is similar to what you would need for Aggregate. You can checkout the [Dockerfile.dev](https://github.com/opendatakit/sync-endpoint-containers/blob/master/Dockerfile.dev) and just use your Aggregate war. You'd need to strip out our security settings though.

One warning I can give you about putting Aggregate in a Docker container is that you'll need be careful about URLs. Aggregate constructs its own redirect URLs and you'll need to configure them properly. With Docker you need to be particularly careful about ports.

I have never seen the error you're getting. I would recommend trying to get Aggregate working in a VM and then move that configuration over into your Docker container.

**Comment by farrukharshad** [comment]
Thank you very much for the detailed explanation.
