### ISSUE TITLE
ODKAggregateAppEngineUpdater.jar errors out with Java 9

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/aggregate#228]
When I try to install Aggregate on macOS running Java 9, I get this message. To reproduce, double-click the uploadAggregateToAppEngine.app app and hit getToken.

```
getToken :  Beginning interaction for module default...
getToken!:  Mar 16, 2018 2:46:03 PM com.google.appengine.tools.admin.Application guessContentTypeFromName
getToken!:  WARNING: Error identify mimetype for /api/appversion/getresourcelimits
getToken!:  java.lang.NoClassDefFoundError: javax/activation/FileTypeMap
getToken!:  	at com.google.appengine.tools.admin.Application.guessContentTypeFromName(Application.java:584)
getToken!:  	at com.google.appengine.tools.admin.AbstractServerConnection.send1(AbstractServerConnection.java:334)
getToken!:  	at com.google.appengine.tools.admin.AbstractServerConnection.send(AbstractServerConnection.java:317)
getToken!:  	at com.google.appengine.tools.admin.AbstractServerConnection.post(AbstractServerConnection.java:296)
getToken!:  	at com.google.appengine.tools.admin.NoLoggingClientDeploySender.send(NoLoggingClientDeploySender.java:35)
getToken!:  	at com.google.appengine.tools.admin.ResourceLimits.remoteRequest(ResourceLimits.java:174)
getToken!:  	at com.google.appengine.tools.admin.ResourceLimits.request(ResourceLimits.java:139)
getToken!:  	at com.google.appengine.tools.admin.AppAdminImpl.getResourceLimits(AppAdminImpl.java:328)
getToken!:  	at com.google.appengine.tools.admin.AppCfg$ResourceLimitsInfoAction.execute(AppCfg.java:1983)
getToken!:  	at com.google.appengine.tools.admin.AppCfg.executeAction(AppCfg.java:393)
getToken!:  	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:216)
getToken!:  	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:116)
getToken!:  	at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:112)
getToken!:  Caused by: java.lang.ClassNotFoundException: javax.activation.FileTypeMap
getToken!:  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
getToken!:  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
getToken!:  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
getToken!:  	... 13 more
getToken!:  
status :  Action Succeeded!
```

The app runs `java -jar ./ODKAggregateAppEngineUpdater.jar` and when I run that command with Java 1.8, it works great.

**Comment by yanokwa** [comment]
@ggalmazor This is a blocker for release, so prioritize it.

**Comment by ggalmazor** [comment]
So, these messages appear in the log window, but the app gets uploaded anyway. I'll review this but maybe plan b could be to just silence those messages?

**Comment by ggalmazor** [comment]
OK, plan A has worked: updating to AppEngine SDK 1.9.63 solved the error messages. Some normal warnings remain while removing the existing apps before uploading the new, but that's normal.
